project:
  type: website

website:
  title: "Yamato Igarashi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: japanese.qmd
        text: Japanese/日本語

format:
  html:
    theme: Yeti
    css: styles.css
    toc: false
    link-external-newwindow: true

execute:
  freeze: false
